export const FETCH_CONTACTS = "FETCH_CONTACTS";

export const FETCH_CONTACT = "FETCH_CONTACT";

export const POST_CONTACT = "POST_CONTACT";

export const DELETE_CONTACT = "DELETE_CONTACT";

export const UPDATE_CONTACT = "UPDATE_CONTACT";
